# Generated by Django 6.0.4 on 2026-05-23 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_category_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис завдання')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Макс. бал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Відповідь')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'Очікує перевірки'), ('graded', 'Оцінено')], default='pending', max_length=10, verbose_name='Статус')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('feedback', models.TextField(blank=True, verbose_name='Коментар викладача')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Здано')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Оцінено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Завдання')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Відповідь на завдання',
                'verbose_name_plural': 'Відповіді на завдання',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'assignment'], name='idx_sub_student_assign')],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
