# Generated by Django 6.0.4 on 2026-05-24 10:39

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[apps.courses.models.validate_safe_file_10mb], verbose_name='Файл'),
        ),
    ]
