# Generated by Django 6.0.4 on 2026-05-13 17:57

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.validate_image_file], verbose_name='Аватар'),
        ),
    ]
