# Generated by Django 6.0.4 on 2026-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], db_index=True, default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
