# Generated by Django 6.0.4 on 2026-05-13 17:57

import apps.courses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecomment_courserating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='materials/', validators=[apps.courses.models.validate_safe_file_10mb], verbose_name='Файл'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'course'], name='idx_enroll_student_course'),
        ),
    ]
