# Generated by Django 5.1.4 on 2026-04-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Бал (%)')),
                ('passed', models.BooleanField(verbose_name='Пройдено')),
                ('answers', models.JSONField(default=list, help_text='Масив обраних індексів', verbose_name='Відповіді')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='Прохідний бал (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Запитання')),
                ('options', models.JSONField(help_text='Масив рядків, напр. ["Варіант A", "Варіант B", "Варіант C"]', verbose_name='Варіанти відповідей')),
                ('correct_answer', models.PositiveIntegerField(help_text='Індекс (починаючи з 0) правильного варіанту', verbose_name='Індекс правильної відповіді')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_module.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Запитання',
                'verbose_name_plural': 'Запитання',
                'ordering': ['order'],
            },
        ),
    ]
