# Generated by Django 6.0.4 on 2026-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = без обмеження', verbose_name='Обмеження часу (хвилини)'),
        ),
    ]
