# Generated by Django 6.0.4 on 2026-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_module', '0004_testresult_idx_result_student_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list, help_text='Масив правильних відповідей (індекси для multiple, рядки для text)', verbose_name='Правильні відповіді'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Одна правильна відповідь'), ('multiple', 'Кілька правильних відповідей'), ('text', 'Текстова відповідь')], default='single', max_length=20, verbose_name='Тип питання'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.PositiveIntegerField(blank=True, help_text='Індекс (починаючи з 0) правильного варіанту (для single)', null=True, verbose_name='Індекс правильної відповіді'),
        ),
    ]
